# Generated by Django 3.2.3 on 2021-07-08 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamjournal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalpost',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
