# Generated by Django 3.2.4 on 2021-07-08 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dreamjournal', '0002_alter_journalpost_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalpost',
            name='followers',
        ),
    ]
