# Generated by Django 3.2.3 on 2021-06-20 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dreamjournal', '0004_auto_20210620_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_id',
            new_name='post_title',
        ),
    ]
